### ISSUE TITLE
Formatting of files doesn't follow dart formatter

### ISSUE THREAD

**Issue by tajchert** [MohiuddinM/i18n#13]
This is and issue at our CI server as we check to make sure all files follow dart formatting by executing:
`flutter format lib/ test/ test_driver/ --set-exit-if-changed`

However if we generate i18n labels with:
`flutter pub run build_runner build --delete-conflicting-outputs`

The output doesn't follow dart formatting and results in failed CI build unless person remembers to reformat files. 
What is visible line max length is not enforced as well there are tabs instead of spaces:

![image](https://user-images.githubusercontent.com/2962633/110224376-60172800-7edb-11eb-858f-cbb4b928d7d8.png)

This is also related to the fact that dart formatter [doesn't allow to ignore some files - issue 864](https://github.com/dart-lang/dart_style/issues/864)

**Comment by MohiuddinM** [comment]
I use `flutter format` too but never ran into a problem. Generally you don't check in generated file to git. Instead a good practice is to generate them as part of the CI, after the formatting has been checked. So you have 2 solutions: delete generated files from your git and only generate in CI when needed, or use an auto-commit bot which will keep your repository formatted even if you forget :).

**Comment by simolus3** [comment]
Still, would it be possible to make this builder emit formatted files? It is generally considered a bad practice to edit generated files because then they will be unnecessarily rebuilt after running `build_runner` again. So even a pre-commit hook isn't a great workaround, and manually changing files gets really annoying with `build_runner watch`. Virtually all other builders emit formatted files as well.

I'm happy to open a PR to make this builder emit formatted files if desired.

**Comment by MohiuddinM** [comment]
@simolus3 It will be great if you can send a PR with the requested change.
